name: .NET Core CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Verifica o código
    - name: Check out code
      uses: actions/checkout@v3

    # Instala o .NET SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 

    # Restaura dependências usando o .NET CLI
    - name: Restore dependencies
      run: dotnet restore

    # Compila a aplicação
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Roda os testes
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
